# Generated by Django 5.2 on 2025-04-27 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cartitem_options_alter_cartitem_product'),
        ('catalog', '0004_initial'),
        ('places', '0002_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='place',
        ),
        migrations.RemoveField(
            model_name='productoption',
            name='product',
        ),
        migrations.AlterField(
            model_name='place',
            name='categories',
            field=models.ManyToManyField(related_name='places', to='catalog.category', verbose_name='Категории товаров'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductOption',
        ),
    ]
