# Generated by Django 5.2 on 2025-05-01 12:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0005_remove_address_place_place_addresses"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="products",
        ),
    ]
