# Generated by Django 5.2 on 2025-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0010_remove_placetype_code_placetype_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placetype",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Уникальный тег"),
        ),
    ]
