# Generated by Django 5.2 on 2025-06-17 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0011_alter_placetype_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="type",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="places.placetype",
                verbose_name="Тип заведения",
            ),
        ),
    ]
