# Generated by Django 5.2 on 2025-06-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("places", "0012_alter_place_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="place",
            name="type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="places.placetype",
                verbose_name="Тип заведения",
            ),
        ),
    ]
