# Generated by Django 5.2 on 2025-05-01 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('ready', 'Готов к выдаче'), ('issued', 'Выдан'), ('canceled', 'Отменен')], default='created', max_length=20, verbose_name='Статус'),
        ),
    ]
