# Generated by Django 5.2 on 2025-04-27 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0002_remove_cartitem_unique_product_in_cart"),
        ("catalog", "0004_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="options",
            field=models.ManyToManyField(
                blank=True, to="catalog.productoption", verbose_name="Опции"
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="catalog.product",
                verbose_name="Товар",
            ),
        ),
    ]
