# Generated by Django 5.2 on 2025-05-14 19:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0006_cart_session_key_alter_cart_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="session_key",
        ),
    ]
