# Generated by Django 5.2 on 2025-04-27 21:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="place",
        ),
    ]
