# Generated by Django 5.1.4 on 2025-05-09 23:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0008_alter_product_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=ckeditor.fields.RichTextField(blank=True, verbose_name="Описание"),
        ),
    ]
